name: finpay_gold
version: "1.0.0"
config-version: 2

profile: finpay_gold

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  finpay_gold:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
