"""S9 — synthetic OLTP generation tests, run against the real local Silver
snapshot (already generated by S3-S6; no API calls, Silver/Bronze untouched —
this package only reads already-published Silver Parquet files)."""

from datetime import datetime

import pytest

from src.synthetic import generators, pipeline, reference
from src.synthetic.common import SEED
from src.synthetic.validation import SyntheticDataQualityError, validate_all

pytestmark = pytest.mark.filterwarnings("ignore")


@pytest.fixture(scope="module")
def ref():
    return reference.load_reference()


@pytest.fixture(scope="module")
def result(ref):
    return pipeline.run(write_output=False)


# ---- determinism / reproducibility ----


def test_generation_is_deterministic_given_same_seed(ref):
    t1 = pipeline.generate_all_tables(ref, seed=SEED)
    t2 = pipeline.generate_all_tables(ref, seed=SEED)
    for name in t1:
        assert t1[name] == t2[name]


def test_different_seed_produces_different_transactions(ref):
    t1 = pipeline.generate_all_tables(ref, seed=SEED)
    t2 = pipeline.generate_all_tables(ref, seed=SEED + 1)
    assert t1["transactions"] != t2["transactions"]


def test_pipeline_run_reproduces_identical_output_across_calls():
    r1 = pipeline.run(write_output=False)
    r2 = pipeline.run(write_output=False)
    assert r1["tables"] == r2["tables"]
    assert r1["gross_approved_transaction_amount"] == r2["gross_approved_transaction_amount"]


# ---- expected row counts ----


def test_expected_row_counts(result):
    counts = result["row_counts"]
    assert counts["clients"] == 12
    assert counts["programs"] == 8
    assert counts["campaigns"] == 12
    assert counts["offers"] == 20
    assert counts["cardholders"] == 200
    assert 200 <= counts["card_tokens"] <= 400  # 1-2 tokens per cardholder
    assert counts["transactions"] == 4000


def test_transaction_events_row_count_matches_authorization_plus_capture_plus_reversal(result):
    events = result["tables"]["transaction_events"]
    transactions = result["tables"]["transactions"]
    approved = sum(1 for t in transactions if t["status"] == "APPROVED")
    auth = sum(1 for e in events if e["event_type"] == "AUTHORIZATION")
    capture = sum(1 for e in events if e["event_type"] == "CAPTURE")
    reversal = sum(1 for e in events if e["event_type"] == "REVERSAL")
    assert auth == len(transactions)
    assert capture == approved
    assert auth + capture + reversal == len(events)


def test_settlement_count_equals_approved_transaction_count(result):
    transactions = result["tables"]["transactions"]
    settlements = result["tables"]["settlements"]
    approved = sum(1 for t in transactions if t["status"] == "APPROVED")
    assert len(settlements) == approved


def test_reconciliation_count_equals_settlement_count(result):
    assert len(result["tables"]["reconciliation"]) == len(result["tables"]["settlements"])


# ---- PK uniqueness ----


def test_primary_keys_unique(result):
    tables = result["tables"]
    for name, key in [
        ("clients", "client_id"),
        ("programs", "program_id"),
        ("campaigns", "campaign_id"),
        ("offers", "offer_id"),
        ("cardholders", "cardholder_id"),
        ("card_tokens", "token_id"),
        ("transactions", "transaction_id"),
        ("transaction_events", "event_id"),
        ("settlements", "settlement_id"),
        ("reconciliation", "reconciliation_id"),
        ("reward_events", "reward_id"),
    ]:
        values = [r[key] for r in tables[name]]
        assert len(values) == len(set(values)), f"{name}.{key} has duplicates"


def test_settlement_and_reconciliation_are_one_to_one(result):
    settlements = result["tables"]["settlements"]
    reconciliation = result["tables"]["reconciliation"]
    txn_ids = [s["transaction_id"] for s in settlements]
    assert len(txn_ids) == len(set(txn_ids))  # one settlement per transaction
    settlement_ids = [r["settlement_id"] for r in reconciliation]
    assert len(settlement_ids) == len(set(settlement_ids))  # one reconciliation per settlement


# ---- reference validity ----


def test_clients_reference_real_distinct_leis(result, ref):
    real_leis = {r["lei"] for r in ref["legal_entity"]}
    client_leis = [c["lei"] for c in result["tables"]["clients"]]
    assert all(lei in real_leis for lei in client_leis)
    assert len(client_leis) == len(set(client_leis))  # no client reuses another's LEI


def test_transactions_reference_real_merchants(result, ref):
    real_merchant_ids = {r["merchant_id"] for r in ref["merchant"]}
    assert all(t["merchant_id"] in real_merchant_ids for t in result["tables"]["transactions"])


def test_transactions_reference_real_mcc_codes(result, ref):
    real_mcc_codes = {r["mcc_code"] for r in ref["mcc"]}
    assert all(t["mcc_code"] in real_mcc_codes for t in result["tables"]["transactions"])


def test_transactions_reference_real_currency_codes(result, ref):
    real_currency_codes = {r["currency_code"] for r in ref["iso_currency"]}
    assert all(t["currency_code"] in real_currency_codes for t in result["tables"]["transactions"])


def test_card_tokens_reference_real_bin_ranges(result, ref):
    real_bins = {r["bin_range"] for r in ref["card_issuer"]}
    assert all(t["bin_range"] in real_bins for t in result["tables"]["card_tokens"])


def test_offers_eligible_mcc_when_set_is_real(result, ref):
    real_mcc_codes = {r["mcc_code"] for r in ref["mcc"]}
    for offer in result["tables"]["offers"]:
        if offer["eligible_mcc_code"] is not None:
            assert offer["eligible_mcc_code"] in real_mcc_codes


# ---- lifecycle ordering / boundary cases ----


def test_every_transaction_has_exactly_one_authorization_event(result):
    events_by_txn: dict[str, list] = {}
    for e in result["tables"]["transaction_events"]:
        events_by_txn.setdefault(e["transaction_id"], []).append(e)
    for txn in result["tables"]["transactions"]:
        types = [e["event_type"] for e in events_by_txn[txn["transaction_id"]]]
        assert types.count("AUTHORIZATION") == 1
        assert types[0] == "AUTHORIZATION"


def test_declined_transactions_have_no_capture_no_settlement_no_reward(result):
    settled_txn_ids = {s["transaction_id"] for s in result["tables"]["settlements"]}
    rewarded_txn_ids = {r["transaction_id"] for r in result["tables"]["reward_events"]}
    events_by_txn: dict[str, list] = {}
    for e in result["tables"]["transaction_events"]:
        events_by_txn.setdefault(e["transaction_id"], []).append(e)

    declined = [t for t in result["tables"]["transactions"] if t["status"] == "DECLINED"]
    assert len(declined) > 0  # sanity: the boundary case actually occurs
    for txn in declined:
        assert txn["transaction_id"] not in settled_txn_ids
        assert txn["transaction_id"] not in rewarded_txn_ids
        types = [e["event_type"] for e in events_by_txn[txn["transaction_id"]]]
        assert "CAPTURE" not in types
        assert "REVERSAL" not in types
        assert txn["decline_reason"] is not None
        assert txn["auth_code"] is None


def test_reversal_only_occurs_after_a_capture_and_some_reversals_exist(result):
    events_by_txn: dict[str, list] = {}
    for e in result["tables"]["transaction_events"]:
        events_by_txn.setdefault(e["transaction_id"], []).append(e)
    reversal_txns = [tid for tid, evs in events_by_txn.items() if any(e["event_type"] == "REVERSAL" for e in evs)]
    assert len(reversal_txns) > 0  # sanity: the scenario actually occurs
    for tid in reversal_txns:
        evs = sorted(events_by_txn[tid], key=lambda e: e["event_timestamp"])
        types = [e["event_type"] for e in evs]
        assert types == ["AUTHORIZATION", "CAPTURE", "REVERSAL"]
        auth_ts = datetime.fromisoformat(evs[0]["event_timestamp"])
        capture_ts = datetime.fromisoformat(evs[1]["event_timestamp"])
        reversal_ts = datetime.fromisoformat(evs[2]["event_timestamp"])
        assert auth_ts <= capture_ts <= reversal_ts


# ---- settlement / reconciliation relationships ----


def test_settlement_amount_equals_transaction_amount(result):
    txn_by_id = {t["transaction_id"]: t for t in result["tables"]["transactions"]}
    for s in result["tables"]["settlements"]:
        assert s["settlement_amount"] == txn_by_id[s["transaction_id"]]["amount"]


def test_settlement_net_amount_arithmetic(result):
    for s in result["tables"]["settlements"]:
        assert round(s["settlement_amount"] - s["fee_amount"], 2) == s["net_amount"]


def test_reconciliation_arithmetic_variance_equals_actual_minus_expected(result):
    for r in result["tables"]["reconciliation"]:
        assert round(r["actual_amount"] - r["expected_amount"], 2) == r["variance"]


def test_reconciliation_matched_rows_have_zero_variance_and_exceptions_do_not(result):
    matched = [r for r in result["tables"]["reconciliation"] if r["match_status"] == "MATCHED"]
    exceptions = [r for r in result["tables"]["reconciliation"] if r["match_status"] == "EXCEPTION"]
    assert len(matched) > 0 and len(exceptions) > 0  # both outcomes actually occur
    assert all(r["variance"] == 0 for r in matched)
    assert all(r["variance"] != 0 for r in exceptions)


def test_control_total_gross_approved_amount_equals_gross_settlement_amount(result):
    assert result["gross_approved_transaction_amount"] == result["gross_settlement_amount"]


def test_control_total_reconciliation_expected_equals_settlement_total(result):
    assert result["reconciliation_expected_total"] == result["gross_settlement_amount"]


# ---- reward qualification ----


def test_reward_qualification_consistency(result):
    for r in result["tables"]["reward_events"]:
        if r["qualification_status"] == "QUALIFIED":
            assert r["reward_amount"] > 0
        else:
            assert r["reward_amount"] == 0


def test_reward_events_only_reference_approved_transactions(result):
    txn_by_id = {t["transaction_id"]: t for t in result["tables"]["transactions"]}
    for r in result["tables"]["reward_events"]:
        assert txn_by_id[r["transaction_id"]]["status"] == "APPROVED"


def test_reward_events_both_qualification_outcomes_occur(result):
    statuses = {r["qualification_status"] for r in result["tables"]["reward_events"]}
    assert "QUALIFIED" in statuses
    assert "NOT_QUALIFIED" in statuses


# ---- synthetic-data tagging ----


def test_every_table_tagged_as_synthetic(result):
    for name, records in result["tables"].items():
        assert all(r.get("source_type") == "synthetic" for r in records), name


# ---- overall validator ----


def test_validate_all_passes_on_the_real_generated_dataset(result, ref):
    report = validate_all(result["tables"], ref)
    assert report["passed"] is True


def test_pipeline_run_raises_file_not_found_without_a_silver_snapshot(tmp_path):
    with pytest.raises(FileNotFoundError):
        pipeline.run(silver_root=tmp_path / "no_such_silver_dir", write_output=False)
